module.exports = {
    /*
     * Additional sizes to be generated.
     * 57x57 and 192x192 will be generated by default
     */
    appleSizes: [180, 152, 144, 120, 114, 76, 72],
    precomposed: true,
};
